title: "Pediatric ECG Guide"
description: "A concise, clinical guide to pediatric ECGs"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Site options
markdown: kramdown
exclude:
  - Gemfile.lock

# just-the-docs options (examples you can tweak)
just_the_docs:
  homepage: index
  logo: assets/img/logo.png
  search: true
  toc: true
  show_sidebar: true
